INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '9.00', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '10.30', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '12.00', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '13.30', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '15.00', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '16.30', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '18.00', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '19.30', '1', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '21.00', '1', NULL);

INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '9.00', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '10.30', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '13.30', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '12.00', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '15.00', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '16.30', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '18.00', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '19.30', '2', NULL);
INSERT INTO `reserva` (`id`, `disponible`, `fecha`, `hora`, `pista_id`, `usuario_id`) VALUES (NULL, b'0', '2019-11-18', '21.00', '2', NULL);